config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show, :index] do
    collection do
      get 'activate'
    end
    member do
      post 'admin'
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    collection do
      get 'search'
      post 'search_results'
    end
    resource :albums, only: [:new]
  end
  resources :albums, except: [:index, :new] do
    resource :track, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :destroy]
  end

  root to: 'bands#index'

end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  body       :text             not null
#  user_id    :integer          not null
#  track_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Note < ActiveRecord::Base
  validates :body, :user_id, :track_id, presence: true

  belongs_to :user
  belongs_to :track
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :check_login

  def create
    note = Note.new(note_params)
    note.user_id = current_user.id
    note.track_id = params[:track_id]
    note.save
    redirect_to track_url(params[:track_id])
  end

  def destroy
    note = Note.find(params[:id])
    if current_user.id = note.user_id || current_user.admin
      Note.destroy(params[:id])
      redirect_to track_url(params[:track_id])
    else
      render text: "Forbidden: You did not author this note." , status: 403
    end

  end

  private

  def note_params
    params.require(:note).permit(:body)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<form action="<%= track_notes_url(@track) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="note[body]">Write a note about this track</label> <br />
  <textarea name="note[body]" rows="8" cols="40"></textarea>
  <button>Submit</button>
</form>

app/views/notes/_note.html.erb
<h4>Author E-Mail: <%= note.user.email %></h4>
<p>
  <%= note.body %>
</p>
<% if current_user.id == note.user_id || current_user.admin %>
  <%= link_to 'Delete Note', track_note_url(@track, note), method: :delete %>
<% end %>