config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show, :index] do
    collection do
      get 'activate'
    end
    member do
      post 'admin'
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    collection do
      get 'search'
      post 'search_results'
    end
    resource :albums, only: [:new]
  end
  resources :albums, except: [:index, :new] do
    resource :track, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :destroy]
  end

  root to: 'bands#index'

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  lyrics      :text
#  bonus_track :boolean
#  album_id    :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Track < ActiveRecord::Base
  validates :title, :album_id, presence: true

  belongs_to :album
  has_many :notes
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :check_login

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      @album = Album.find(@track.album_id)
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    track = Track.find(params[:id])
    track.update(track_params)
    redirect_to track_url(track)
  end

  def show
    @track = Track.includes(:album).find(params[:id])
  end

  def destroy
    Track.destroy(params[:id])
    redirect_to root_url
  end

  private

  def track_params
    params.require(:track).permit(:title, :album_id, :lyrics, :bonus_track)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  include ERB::Util

  def ugly_lyrics(lyrics)
    new_lyrics = lyrics.split("\n").map { |line| "&#9835;" + line }
    formatted = "<pre>#{new_lyrics.join}</pre>".html_safe
    formatted
  end
end

app/views/tracks/edit.html.erb
<h1>Edit Track: <%= @track.title %></h1>
<% @track.errors.full_messages.each do |msg| %>
  <h3>Errors</h3>
  <div>
    <%= msg %>
  </div>
<% end %>
<form action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="track[album_id]" value="<%= @track.album.id %>">
  <input  name="track[title]" placeholder="Track Title" value="<%= @track.title %>"> <br />
  <label for="track[bonus_track]">Bonus Track?</label> <br />
  <input type="radio" name="track[bonus_track]" value="true" <%= "checked" if @track.bonus_track %>>Yes
  <input type="radio" name="track[bonus_track]" value="false" "checked" unless @track.bonus_track>No <br />
  <label for="track[lyrics]">Lyrics</label> <br />
    <textarea name="track[lyrics]" rows="8" cols="40"><%= @track.lyrics %></textarea>
  <button>Submit</button>
</form>

app/views/tracks/new.html.erb
<h1>Create Track For Album: <%= @album.title %></h1>
<% @track.errors.full_messages.each do |msg| %>
  <h3>Errors</h3>
  <div>
    <%= msg %>
  </div>
<% end %>
<form action="<%= tracks_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="track[album_id]" value="<%= @album.id %>">
  <input  name="track[title]" placeholder="Track Title"> <br />
  <label for="track[bonus_track]">Bonus Track?</label> <br />
  <input type="radio" name="track[bonus_track]" value="true">Yes
  <input type="radio" name="track[bonus_track]" value="false">No <br />
  <label for="track[lyrics]">Lyrics</label> <br />
  <textarea name="track[lyrics]" rows="8" cols="40"></textarea>
  <button>Submit</button>
</form>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>
<h3>Album: <%= link_to @track.album.title, album_url(@track.album) %></h3>
<% if @track.bonus_track %>
  <p>
    Bonus Track!
  </p>
<% end %>

<h3>Lyrics</h3>
<p>
  <%= ugly_lyrics(@track.lyrics) %>
</p>
<%= link_to "Edit Track", edit_track_url(@track) %>
<%= link_to "Delete Track", track_url(@track), method: :delete %>
<h3>Notes</h3>
<%= render 'notes/form' %>
<% @track.notes.each do |note| %>
  <%= render 'notes/note'  , note: note%>
<% end %>