config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show, :index] do
    collection do
      get 'activate'
    end
    member do
      post 'admin'
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    collection do
      get 'search'
      post 'search_results'
    end
    resource :albums, only: [:new]
  end
  resources :albums, except: [:index, :new] do
    resource :track, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :destroy]
  end

  root to: 'bands#index'

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string
#  live_album :boolean
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  validates :title, :band_id, presence: true

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :check_login

  def new
    @band = Band.find(params[:band_id])
    @bands = Band.all
  end

  def create
    album = Album.new(album_params)
    if album.save
      redirect_to root_url
    else
      redirect_to action: 'new', band_id: album_params[:band_id]
    end
  end

  def show
    @album = Album.includes(:tracks, :band).find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    album = Album.find(params[:id])
    album.update(album_params)
    redirect_to album_url(album)
  end

  private

  def album_params
    params.require(:album).permit(:live_album, :title, :band_id)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<h1>Edit Album: <%= @album.title %></h1>
<form  action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="album[band_id]" value="<%= @album.band.id %>">
  <input  name="album[title]" placeholder="Album Title" value="<%= @album.title %>"> <br />
  <label for="album[live_album]">Live or Studio?</label> <br />
  <input type="radio" name="album[live_album]" <%= "checked" unless @album.live_album %> value="false">Studio
  <input type="radio" name="album[live_album]" <%= "checked" if @album.live_album %> value="true">Live <br />
  <button>Submit</button>
</form>

app/views/albums/new.html.erb
<h1>Create Album For <%= @band.name %></h1>
<form action="<%= albums_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="album[band_id]" value="<%= @band.id %>">
  <input  name="album[title]" placeholder="Album Title"> <br />
  <label for="album[live_album]">Live or Studio?</label> <br />
  <input type="radio" name="album[live_album]" value="false">Studio
  <input type="radio" name="album[live_album]" value="true">Live <br />
  <button>Submit</button>
</form>
<select name="album[band_id]">
  <% @bands.each do |band| %>
    <option <%= "selected" if band.id = @band.id %> value="<%= band.id %>">
      <%= band.name %>
    </option>
  <% end %>
</select>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<% if @album.live_album %>
  <p>
    Recorded Live
  </p>
<% end %>
<p>
  By: <%= link_to @album.band.name, band_url(@album.band) %>
</p>
<h3>Tracks</h3>
<% @album.tracks.each do |track| %>
  <ul>
    <li><%= link_to track.title, track_url(track) %></li>
  </ul>
<% end %>
<%= button_to "New Track", new_album_track_url(@album), method: :get %>