config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show, :index] do
    collection do
      get 'activate'
    end
    member do
      post 'admin'
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    collection do
      get 'search'
      post 'search_results'
    end
    resource :albums, only: [:new]
  end
  resources :albums, except: [:index, :new] do
    resource :track, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :destroy]
  end

  root to: 'bands#index'

end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :check_login
  def new
    @band = Band.new
  end

  def index
    @bands = Band.all
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def show
    @band = Band.includes(:albums).find(params[:id])
  end

  def edit
    @band = Band.find(params[:id])
  end

  def destroy
    Band.destroy(params[:id])
    redirect_to bands_url
  end

  def update
    band = Band.find(params[:id])
    band.update(band_params)
    redirect_to band_url(band)
  end

  def search_results
    @bands = Band.where("lower(name) LIKE ?", "%#{params[:q].downcase}%")
  end

  def search
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/edit.html.erb
<h1>Edit Band</h1>
<% @band.errors.full_messages.each do |msg| %>
  <h3>Errors</h3>
  <div>
    <%= msg %>
  </div>
<% end %>
<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch" />
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input  name="band[name]" placeholder="band name" value="<%= @band.name %>"/>
  <button>Submit</button>
</form>

app/views/bands/index.html.erb
<h1>All Bands</h1>
<ul>
  <% @bands.each do |band| %>
    <li>
      <%= link_to band.name, band_url(band) %>
    </li>
  <% end %>
</ul>
<%= link_to "Create Band", new_band_url %>

app/views/bands/new.html.erb
<h1>Create Band</h1>
<% @band.errors.full_messages.each do |msg| %>
  <h3>Errors</h3>
  <div>
    <%= msg %>
  </div>
<% end %>
<form action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input  name="band[name]" placeholder="band name" />
  <button>Submit</button>
</form>

app/views/bands/search.html.erb
<form action="<%= search_results_bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input  name="q" placeholder="enter band name" >
  <button>Submit</button>
</form>

app/views/bands/search_results.html.erb
<% @bands.each do |band| %>
  <%= link_to band.name, band_url(band) %>
<% end %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<%= button_to "Edit", edit_band_url(@band), method: :get %>
<%= button_to "Delete", band_url(@band), method: :delete %>
<h3>Albums</h3>
<%= button_to "New Album", new_band_albums_url(@band), method: :get %>
<ul>
  <% @band.albums.each do |album| %>
    <li><%= link_to album.title, album_url(album) %></li>
  <% end %>
</ul>
<%= link_to "All Bands", bands_url %>